### ISSUE TITLE
Error at line 287 in  basis_layers.py

### ISSUE THREAD

**Issue by exapde** [TUM-DAML/gemnet_pytorch#2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ngoccuongnguyen/GitHub/gemnet_pytorch/gemnet/model/gemnet.py", line 14, in <module>
    from .layers.basis_layers import BesselBasisLayer, SphericalBasisLayer, TensorBasisLayer
  File "/Users/ngoccuongnguyen/GitHub/gemnet_pytorch/gemnet/model/layers/basis_layers.py", line 287
    Kmax = if sph.shape[0]==0 else torch.max(torch.max(Kidx + 1), torch.tensor(0))  
           ^
SyntaxError: invalid syntax

**Comment by gasteigerjo** [comment]
Fixed in 96300afcb7
